server:
  name: "gin-viper-app"
  host: "127.0.0.1"
  port: 8089
  mode: "debug"  # debug, release, test

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "test_db"
  charset: "utf8mb4"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

log:
  debug: true
  enable_file: true
  enable_console: true
  file_path: "./logs/app.log"